#bug test
language: java
notifications:
  email: false
jdk:
  - oraclejdk8
  - openjdk7
before_install:
  - sed -i 's/<module>google-api-client-android<\/module>//'  pom.xml
  - sed -i 's/<module>google-api-client-assembly<\/module>//' pom.xml
